version: '3.9'
services:
  postgres-db:
    image: postgres:15
    container_name: clevertec-carshowroom
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: clevertec-carshowroom
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: